### ISSUE TITLE
OAuth redirect not working

### ISSUE THREAD

**Issue by ehowe** [LosFuzzys/MediaWiki-OAuth2-Github#5]
Hi,

I've been trying to get this extension working for a while now, but I'm not having much luck.  I installed it according to the directions, and configured it with the appropriate client id and secret.  When I got to the login page, I see the "Login with Github" link, but whenever I click it, I'm redirected back to the homepage, instead of to Github like I would expect.

Do you have an tips on what I'm doing wrong?

**Comment by stefan2904** [comment]
One theory:  If your Wiki is completely closed (login required for every page), you need to whitelist the plugin's Special: page (to allow it to be opened without login, since you use it to login) in the Mediawiki config.

(I can look up the line in our config if you want, but I don't have access right now.)

**Comment by ehowe** [comment]
I do have a completely closed wiki, so that seems like a probable candidate.  I'll check that out and report back.  Thanks!

**Comment by stefan2904** [comment]
from our *LocalSettings.php*:
```php
// whitelist oauth hooks for non-authed users:
$wgWhitelistRead = array("Special:OAuth2Github");

// load oauth2-github extention
wfLoadExtension( 'MediaWiki-OAuth2-Github' );

```

**Comment by ehowe** [comment]
That was the problem, thanks for pointing me in the right direction!
